name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see! You can paste screenshots here.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of the DAG Monitor are you running?
      options:
        - 1.0 (Default)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: ios
    attributes:
      label: What OS version are you on?
      multiple: false
      options:
        - iOS 16
        - iOS 17
        - iOS 18
        - iPadOS 16
        - iPadOS 17
        - iPadOS 18
        - MacOS 13
        - MacOS 14
        - MacOS 15
      default: 2
    validations:
      required: true
