name: Feature Request
description: Request a feature.
title: "[FeatureRequest]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: problem
    attributes:
      label: Is this related to problem?
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: What do you want to happen?
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Is there an alternative?
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Anything else?
      description: Additional context
      placeholder: Add any other context or screenshots about the feature request here.
    validations:
      required: false
